### ISSUE TITLE
Integrated Pre-Gate sensor supports

### ISSUE THREAD

**Issue by alidaf** [igiannakas/ERCF-v2-mods#1]
Do you have a version with the built-in supports or a .3mf file with painted supports?

**Comment by igiannakas** [comment]
Supports aren’t needed for the rc2 parts - the same applies for the non modified  ones from the rc2 repo. Check here: https://github.com/Enraged-Rabbit-Community/ERCF_v2/tree/rc2/Stls/Filament_Blocks/TD_C9

**Comment by igiannakas** [comment]
Ps. These are only compatible with the RC2 filament blocks!!

**Comment by alidaf** [comment]
Thanks. I may have to try and remix it myself anyway because I have one of the kits with the switches on a circuit board so the orientation of the switches is different.

**Comment by igiannakas** [comment]
there are a couple of different approaches developed since I found the ones I used:

from triple decky repo: https://github.com/gneu42/Triple-Decky/tree/main/STL/ERCF-V2/Rev_C/Rev_C9/Optional%20Pre-gate%20Sensor%20(Experimental)

from the ERCF v2 repo: https://github.com/Enraged-Rabbit-Community/ERCF_v2/blob/rc2/Recommended_Options/ERCT_Buffer/Coupler_Block/Coupler_Block_Lite.stl

I think the latter from ERCF would work for your integrated pcb switches. Basically it’s a trimmed down block to be used without the ERCT.

**Comment by alidaf** [comment]
That's perfect, and a sanity saver. Many thanks.
